// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisitorServices.Data;

namespace VisitorServices.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200923092127_step1")]
    partial class step1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VisitorServices.Entities.BindUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Reason");

                    b.Property<int>("VisitorInformationId");

                    b.HasKey("Id");

                    b.HasIndex("VisitorInformationId")
                        .IsUnique();

                    b.ToTable("BindUsers");
                });

            modelBuilder.Entity("VisitorServices.Entities.VisitorInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Email");

                    b.Property<string>("Governrate");

                    b.Property<string>("IdNumber");

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.ToTable("VisitorInformations");
                });

            modelBuilder.Entity("VisitorServices.Entities.BindUser", b =>
                {
                    b.HasOne("VisitorServices.Entities.VisitorInformation", "VisitorInformation")
                        .WithOne("BindUser")
                        .HasForeignKey("VisitorServices.Entities.BindUser", "VisitorInformationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
